train: ./data/datasets/train/images
val: ./data/datasets/valid/images
test: ./data/datasets/test/images

nc: 4
names: ['AnaYemek', 'Ekmek', 'Icecek', 'YardimciYemek']

roboflow:
  workspace: tepsi-analiz
  project: food-category
  version: 8
  license: CC BY 4.0
  url: https://universe.roboflow.com/tepsi-analiz/food-category/dataset/8